#!/bin/bash

echo "Removing recipes and groups rst files..."
rm -fr book/source/groups book/source/recipes 

echo "Calling cookbook.py"
python3.6 cookbook.py recipes -o book/source


make -C book clean

make -C book html

rm -fr docs/*

touch docs/.nojekyll

cp -r book/build/html/* docs/

