#!/bin/bash

echo "Removing recipes and groups rst files..."
rm -fr book/source/groups book/source/recipes 

echo "Calling cookbook.py"
python3.7 cookbook.py recipes -o book/source

make -C book clean html
#make -C book clean latexpdf
